
# Docker file for SQL Server.

# Connection string to use can be found below.

# Server=localhost;Initial Catalog={database};User=sa;Password=Your_password123;

version: "3.3"

services:

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: Your_password123
        ACCEPT_EULA: Y
    ports:
    - "1433:1433"
