
# Docker file for PostgreSQL.
# Connection string to use can be found below
# User ID=postgres;Password=ThisIsNotAGoodPassword;Host=localhost;Database={database}; Port=54320;

version: "3.3"

services:

  db:
    image: postgres:9.3
    restart: always
    environment:
    - POSTGRES_PASSWORD=ThisIsNotAGoodPassword
    ports:
    - "54320:5432"
