
# Docker file for SQL Server.

version: "3.3"

services:

  db:
    image: postgres:9.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=ThisIsNotAGoodPassword
    ports:
    - "54321:5432"
